[package]
name = "gfx-test"
version = "0.1.0"
authors = ["kryptan"]

[dependencies]
#gfx = "0.12.2"
#gfx_window_glutin = "0.12.0"
#glutin = "0.6"
gfx = "0.13.0"
gfx_window_glutin = "0.13.1"
glutin = "0.7.1"